version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.x
  build:
    commands:
      - dotnet test --verbosity normal AWS.DistributedCacheProvider.sln --configuration Release --logger trx --results-directory ./testresults
reports:
  aws-dotnet-distributed-cache-provider-tests:
    file-format: VisualStudioTrx
    files:
      - '**/*'
    base-directory: './testresults'